#!/bin/sh

test -d out/DEBIAN || mkdir -p out/DEBIAN
test -d out/opt/nginx/bin || mkdir -p out/opt/nginx/bin
test -d out/opt/nginx/conf || mkdir -p out/opt/nginx/conf
test -d out/opt/nginx/logs || mkdir -p out/opt/nginx/logs 
test -d out/opt/nginx/html || mkdir -p out/opt/nginx/html
test -d out/opt/nginx/temp || mkdir -p out/opt/nginx/temp
test -d out/etc/init.d || mkdir -p out/etc/init.d
test -d out/etc/profile.d || mkdir -p out/etc/profile.d

cp debian/control out/DEBIAN/control
cp debian/preinst out/DEBIAN/preinst
cp debian/prerm   out/DEBIAN/prerm
cp debian/postinst out/DEBIAN/postinst
cp debian/postrm   out/DEBIAN/postrm
cp debian/nginx    out/etc/init.d/nginx
cp debian/nginx.sh out/etc/profile.d/nginx.sh
cp objs/nginx out/opt/nginx/bin/nginx
cp conf/* out/opt/nginx/conf/
cp html/* out/opt/nginx/html/

